name: Cypress Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci --prefix backend

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Run backend server
        run: npm run dev --prefix backend & npx wait-on http://localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          project: ./frontend
          start: npm run dev --prefix frontend
          wait-on: 'http://localhost:5173'